env=QA
baseUrl=https://demowebshop.tricentis.com/

# -------------------------
# BROWSER CONFIG
# -------------------------
browser=chrome
headless=false

# -------------------------
# LOGGING CONFIG
# -------------------------
videoMode=on
screenshotOnFailure=true
timeout=30000

# -------------------------
# TEST DATA
# -------------------------
testdata.file=src/test/resources/testdata/users.csv